package com.studiomath.drawview.document.motion

import android.content.Context
import android.graphics.Matrix
import android.graphics.RectF
import android.util.Log
import android.view.GestureDetector
import android.view.MotionEvent
import android.view.ScaleGestureDetector
import com.studiomath.drawview.document.DrawManager.DrawAttachments
import com.studiomath.drawview.document.DrawManager.DrawAttachments.DrawMode
import com.studiomath.drawview.document.DrawViewModel
import kotlin.math.abs

/**
 * Manages native Scale (Pinch-to-zoom) and Translate (Pan) gestures.
 * * It relies on Android's native [ScaleGestureDetector] and [GestureDetector]
 * to provide smooth, highly optimized, and stable viewport manipulations.
 * * @property drawViewModel The ViewModel containing the drawing state and managers.
 */
class OnScaleTranslate(
    private var drawViewModel: DrawViewModel
) {
    companion object {
        private const val TAG = "OnScaleTranslate"

        /** Maximum allowed zoom level. */
        private const val MAX_SCALE = 5f

        /** Minimum allowed zoom level. */
        private const val MIN_SCALE = 0.5f

        /** Maximum pixel distance allowed for over-scrolling before bounds limit the fling. */
        private const val OVERSCROLL_LIMIT = 200
    }

    /** Flag indicating if the gesture interceptor should continue processing the touch event. */
    var continueScaleTranslate = false

    /** Flag indicating whether an active multi-touch pinch-to-zoom gesture is occurring. */
    var isScaling = false

    /** The out-of-bounds horizontal distance (used for elastic bounce-back). */
    var excessX = 0f

    /** The out-of-bounds vertical distance (used for elastic bounce-back). */
    var excessY = 0f

    // Lazy initialization for native detectors (since they require a Context)
    private var scaleDetector: ScaleGestureDetector? = null
    private var gestureDetector: GestureDetector? = null

    // Tracks the focal point during a zoom to allow simultaneous panning (two-finger drag)
    private var lastFocusX = 0f
    private var lastFocusY = 0f

    /**
     * Initializes the native gesture detectors.
     * This is called lazily upon receiving the first touch event.
     * * @param context The Context required by Android's native gesture detectors.
     */
    private fun initDetectors(context: Context) {
        if (scaleDetector != null) return

        // 1. Handler for Pinch-to-Zoom (Scaling)
        scaleDetector = ScaleGestureDetector(context, object : ScaleGestureDetector.SimpleOnScaleGestureListener() {
            override fun onScaleBegin(detector: ScaleGestureDetector): Boolean {
                isScaling = true
                lastFocusX = detector.focusX
                lastFocusY = detector.focusY
                return true
            }

            override fun onScale(detector: ScaleGestureDetector): Boolean {
                val scaleFactor = detector.scaleFactor
                val focusX = detector.focusX
                val focusY = detector.focusY

                val tempMatrix = Matrix(drawViewModel.drawManager.moveMatrix)
                val f = FloatArray(9)
                tempMatrix.getValues(f)

                val currentScale = f[Matrix.MSCALE_X]
                var adjustedScaleFactor = scaleFactor

                // Constrain the scale factor within the allowed MIN_SCALE and MAX_SCALE bounds
                if (currentScale * adjustedScaleFactor < MIN_SCALE) {
                    adjustedScaleFactor = MIN_SCALE / currentScale
                } else if (currentScale * adjustedScaleFactor > MAX_SCALE) {
                    adjustedScaleFactor = MAX_SCALE / currentScale
                }

                // Apply the scaling transformation anchored to the current focal point
                tempMatrix.postScale(adjustedScaleFactor, adjustedScaleFactor, focusX, focusY)

                // Apply the translation (pan) generated by moving the two fingers while zooming
                val dx = focusX - lastFocusX
                val dy = focusY - lastFocusY
                tempMatrix.postTranslate(dx, dy)

                lastFocusX = focusX
                lastFocusY = focusY

                applyMatrixAndRequestDraw(tempMatrix)
                return true
            }

            override fun onScaleEnd(detector: ScaleGestureDetector) {
                isScaling = false
                checkBoundsAndBounceBack()
            }
        })

        // 2. Handler for Single-finger Pan and Fling
        gestureDetector = GestureDetector(context, object : GestureDetector.SimpleOnGestureListener() {
            override fun onDown(e: MotionEvent): Boolean {
                // Stop any ongoing fling animation if the user touches the screen again
                drawViewModel.drawManager.scroller.forceFinished(true)
                return true
            }

            override fun onScroll(e1: MotionEvent?, e2: MotionEvent, distanceX: Float, distanceY: Float): Boolean {
                // Ignore single-finger scroll if a two-finger scaling gesture is currently active
                if (isScaling) return true

                val tempMatrix = Matrix(drawViewModel.drawManager.moveMatrix)
                // Native distanceX/Y are positive when the finger moves up/left.
                // We invert them to map the camera movement correctly.
                tempMatrix.postTranslate(-distanceX, -distanceY)

                applyMatrixAndRequestDraw(tempMatrix)
                return true
            }

            override fun onFling(e1: MotionEvent?, e2: MotionEvent, velocityX: Float, velocityY: Float): Boolean {
                return handleFling(velocityX, velocityY)
            }
        })
    }

    /**
     * Determines whether the motion event should be intercepted by the scaling/translating logic.
     * * @param event The motion event dispatched to the view.
     * @return true if the event should be intercepted.
     */
    fun onInterceptScaleTranslate(event: MotionEvent): Boolean {
        return continueScaleTranslate
    }

    /**
     * Main entry point for processing touch events related to scaling and translating.
     * * @param context The UI Context.
     * @param event The motion event captured by the view.
     */
    fun onScaleTranslate(context: Context, event: MotionEvent) {
        initDetectors(context)

        val action = event.actionMasked

        // Feed the touch event to the native detectors for processing
        scaleDetector?.onTouchEvent(event)
        gestureDetector?.onTouchEvent(event)

        // Check for bounds and bounce-back when the user lifts their finger(s),
        // provided no fling animation was triggered.
        if (action == MotionEvent.ACTION_UP || action == MotionEvent.ACTION_CANCEL) {
            if (drawViewModel.drawManager.scroller.isFinished) {
                checkBoundsAndBounceBack()
            }
        }

        continueScaleTranslate = true
    }

    /**
     * Calculates page boundaries, applies the elastic overscroll effect if needed,
     * and triggers a UI update with the temporary transformation matrix.
     * * @param tempMatrix The temporary matrix representing the new viewport state.
     */
    private fun applyMatrixAndRequestDraw(tempMatrix: Matrix) {
        drawViewModel.drawManager.apply {
            val result = calcPage.applyBounds(tempMatrix, calcPage.contentRect, windowRect)
            excessX = result.first
            excessY = result.second

            val transformedContentRect = RectF(calcPage.contentRect)
            moveMatrix.mapRect(transformedContentRect)

            // Prevent horizontal elastic effect if the content is smaller than the window width
            // and we are not currently scaling.
            if (transformedContentRect.width() < windowRect.width() && !isScaling) {
                excessX = 0f
            }

            elasticMatrix = calcPage.applyElasticEffect(excessX, excessY)
            moveMatrix = Matrix(tempMatrix)

            Log.d(TAG, "onDrawView: moveMatrix = $moveMatrix")
            requestDraw(DrawAttachments(drawMode = DrawMode.SCALE_TRANSLATE))
        }
    }

    /**
     * Checks if the viewport is out of bounds upon gesture release.
     * - If it is out of bounds, it triggers an elastic bounce-back animation.
     * - If it is within bounds, it triggers a high-quality bitmap update to finalize the gesture.
     */
    private fun checkBoundsAndBounceBack() {
        drawViewModel.drawManager.apply {
            calcPage.applyBounds(moveMatrix, calcPage.contentRect, windowRect)

            if (excessX != 0f || excessY != 0f) {
                Log.d(TAG, "Starting Bounce Back animation")
                startAnimateMatrix.set(moveMatrix)

                calcPage.startBounceBackAnimation(
                    excessX, excessY, elasticMatrix,
                    updateCallback = {
                        moveMatrix.set(startAnimateMatrix)
                        requestDraw(
                            DrawAttachments(drawMode = DrawMode.ANIMATE).apply {
                                animationType = DrawAttachments.AnimationType.BOUNCE_BACK
                            }
                        )
                    },
                    onEndCallback = {
                        requestDraw(
                            DrawAttachments(drawMode = DrawMode.UPDATE).apply {
                                update = DrawAttachments.Update.DRAW_BITMAP
                            }
                        )
                    }
                )
            } else {
                // No excess bounds reached. The gesture ended in a valid position.
                // Request a high-quality Bitmap update to "commit" the visual result.
                Log.d(TAG, "Gesture ended within limits, requesting UPDATE DRAW_BITMAP")
                requestDraw(
                    DrawAttachments(drawMode = DrawMode.UPDATE).apply {
                        update = DrawAttachments.Update.DRAW_BITMAP
                    }
                )
            }
        }
    }

    /**
     * Calculates and executes the inertial fling animation when the user swipes and releases quickly.
     * * @param velocityX The initial X velocity of the fling.
     * @param velocityY The initial Y velocity of the fling.
     * @return true if the fling was successfully initiated, false otherwise.
     */
    private fun handleFling(velocityX: Float, velocityY: Float): Boolean {
        // Prevent fling if we are already out of bounds (let bounce-back handle it instead).
        if (excessX != 0f || excessY != 0f) {
            Log.d(TAG, "Fling disabled: out of bounds. Falling back to Bounce Back.")
            checkBoundsAndBounceBack()
            return true
        }

        val manager = drawViewModel.drawManager
        val transformedContentRect = RectF(manager.calcPage.contentRect)
        manager.moveMatrix.mapRect(transformedContentRect)

        val startPointScroller = floatArrayOf(0f, 0f)
        manager.moveMatrix.mapPoints(startPointScroller)

        // Calculate horizontal fling constraints
        val xOffset = startPointScroller[0] - transformedContentRect.left
        var minX = (manager.windowRect.width() - transformedContentRect.width() + xOffset).coerceAtMost(xOffset).toInt()
        var maxX = xOffset.toInt()
        var vX = velocityX.toInt()

        if (transformedContentRect.width() < manager.windowRect.width()) {
            minX = Int.MIN_VALUE
            maxX = Int.MAX_VALUE
            vX = 0
        }

        // Calculate vertical fling constraints
        val yOffset = startPointScroller[1] - transformedContentRect.top
        val minY = (manager.windowRect.height() - transformedContentRect.height() + yOffset).coerceAtMost(0f).toInt()
        val maxY = yOffset.toInt()
        val vY = velocityY.toInt()

        val minVelocity = drawViewModel.configuration.scaledMinimumFlingVelocity

        // Initiate the fling if the velocity exceeds the minimum threshold
        if (abs(vX) > minVelocity || abs(vY) > minVelocity) {
            Log.d(TAG, "Starting Fling with velocity X: $vX, Y: $vY")
            manager.scroller.fling(
                startPointScroller[0].toInt(), startPointScroller[1].toInt(),
                vX, vY,
                minX, maxX, minY, maxY,
                OVERSCROLL_LIMIT, OVERSCROLL_LIMIT
            )

            manager.startAnimateMatrix = Matrix(manager.moveMatrix)
            manager.requestDraw(
                DrawAttachments(drawMode = DrawMode.ANIMATE).apply {
                    animationType = DrawAttachments.AnimationType.FLING
                }
            )
            return true
        }
        return false
    }
}